// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_exchange.proto

// Protobuf Java Version: 3.25.1
package rs.raf.pds.v5.z2.gRPC;

public interface AskDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AskData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double askPrice = 2;</code>
   * @return The askPrice.
   */
  double getAskPrice();

  /**
   * <code>int32 availableShares = 3;</code>
   * @return The availableShares.
   */
  int getAvailableShares();
}
