// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_exchange.proto

// Protobuf Java Version: 3.25.1
package rs.raf.pds.v5.z2.gRPC;

/**
 * Protobuf type {@code AskList}
 */
public final class AskList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AskList)
    AskListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AskList.newBuilder() to construct.
  private AskList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AskList() {
    asks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AskList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_AskList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_AskList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.v5.z2.gRPC.AskList.class, rs.raf.pds.v5.z2.gRPC.AskList.Builder.class);
  }

  public static final int ASKS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<rs.raf.pds.v5.z2.gRPC.AskData> asks_;
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  @java.lang.Override
  public java.util.List<rs.raf.pds.v5.z2.gRPC.AskData> getAsksList() {
    return asks_;
  }
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends rs.raf.pds.v5.z2.gRPC.AskDataOrBuilder> 
      getAsksOrBuilderList() {
    return asks_;
  }
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  @java.lang.Override
  public int getAsksCount() {
    return asks_.size();
  }
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.AskData getAsks(int index) {
    return asks_.get(index);
  }
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.AskDataOrBuilder getAsksOrBuilder(
      int index) {
    return asks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < asks_.size(); i++) {
      output.writeMessage(1, asks_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < asks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, asks_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.v5.z2.gRPC.AskList)) {
      return super.equals(obj);
    }
    rs.raf.pds.v5.z2.gRPC.AskList other = (rs.raf.pds.v5.z2.gRPC.AskList) obj;

    if (!getAsksList()
        .equals(other.getAsksList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAsksCount() > 0) {
      hash = (37 * hash) + ASKS_FIELD_NUMBER;
      hash = (53 * hash) + getAsksList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.v5.z2.gRPC.AskList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.AskList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.AskList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.AskList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.AskList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.AskList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.AskList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.AskList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static rs.raf.pds.v5.z2.gRPC.AskList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static rs.raf.pds.v5.z2.gRPC.AskList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.AskList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.AskList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.v5.z2.gRPC.AskList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AskList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AskList)
      rs.raf.pds.v5.z2.gRPC.AskListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_AskList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_AskList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.v5.z2.gRPC.AskList.class, rs.raf.pds.v5.z2.gRPC.AskList.Builder.class);
    }

    // Construct using rs.raf.pds.v5.z2.gRPC.AskList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (asksBuilder_ == null) {
        asks_ = java.util.Collections.emptyList();
      } else {
        asks_ = null;
        asksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_AskList_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.AskList getDefaultInstanceForType() {
      return rs.raf.pds.v5.z2.gRPC.AskList.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.AskList build() {
      rs.raf.pds.v5.z2.gRPC.AskList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.AskList buildPartial() {
      rs.raf.pds.v5.z2.gRPC.AskList result = new rs.raf.pds.v5.z2.gRPC.AskList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(rs.raf.pds.v5.z2.gRPC.AskList result) {
      if (asksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          asks_ = java.util.Collections.unmodifiableList(asks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.asks_ = asks_;
      } else {
        result.asks_ = asksBuilder_.build();
      }
    }

    private void buildPartial0(rs.raf.pds.v5.z2.gRPC.AskList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.v5.z2.gRPC.AskList) {
        return mergeFrom((rs.raf.pds.v5.z2.gRPC.AskList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.v5.z2.gRPC.AskList other) {
      if (other == rs.raf.pds.v5.z2.gRPC.AskList.getDefaultInstance()) return this;
      if (asksBuilder_ == null) {
        if (!other.asks_.isEmpty()) {
          if (asks_.isEmpty()) {
            asks_ = other.asks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAsksIsMutable();
            asks_.addAll(other.asks_);
          }
          onChanged();
        }
      } else {
        if (!other.asks_.isEmpty()) {
          if (asksBuilder_.isEmpty()) {
            asksBuilder_.dispose();
            asksBuilder_ = null;
            asks_ = other.asks_;
            bitField0_ = (bitField0_ & ~0x00000001);
            asksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAsksFieldBuilder() : null;
          } else {
            asksBuilder_.addAllMessages(other.asks_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              rs.raf.pds.v5.z2.gRPC.AskData m =
                  input.readMessage(
                      rs.raf.pds.v5.z2.gRPC.AskData.parser(),
                      extensionRegistry);
              if (asksBuilder_ == null) {
                ensureAsksIsMutable();
                asks_.add(m);
              } else {
                asksBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<rs.raf.pds.v5.z2.gRPC.AskData> asks_ =
      java.util.Collections.emptyList();
    private void ensureAsksIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        asks_ = new java.util.ArrayList<rs.raf.pds.v5.z2.gRPC.AskData>(asks_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.v5.z2.gRPC.AskData, rs.raf.pds.v5.z2.gRPC.AskData.Builder, rs.raf.pds.v5.z2.gRPC.AskDataOrBuilder> asksBuilder_;

    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public java.util.List<rs.raf.pds.v5.z2.gRPC.AskData> getAsksList() {
      if (asksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(asks_);
      } else {
        return asksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public int getAsksCount() {
      if (asksBuilder_ == null) {
        return asks_.size();
      } else {
        return asksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.AskData getAsks(int index) {
      if (asksBuilder_ == null) {
        return asks_.get(index);
      } else {
        return asksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public Builder setAsks(
        int index, rs.raf.pds.v5.z2.gRPC.AskData value) {
      if (asksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAsksIsMutable();
        asks_.set(index, value);
        onChanged();
      } else {
        asksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public Builder setAsks(
        int index, rs.raf.pds.v5.z2.gRPC.AskData.Builder builderForValue) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.set(index, builderForValue.build());
        onChanged();
      } else {
        asksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public Builder addAsks(rs.raf.pds.v5.z2.gRPC.AskData value) {
      if (asksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAsksIsMutable();
        asks_.add(value);
        onChanged();
      } else {
        asksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public Builder addAsks(
        int index, rs.raf.pds.v5.z2.gRPC.AskData value) {
      if (asksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAsksIsMutable();
        asks_.add(index, value);
        onChanged();
      } else {
        asksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public Builder addAsks(
        rs.raf.pds.v5.z2.gRPC.AskData.Builder builderForValue) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.add(builderForValue.build());
        onChanged();
      } else {
        asksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public Builder addAsks(
        int index, rs.raf.pds.v5.z2.gRPC.AskData.Builder builderForValue) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.add(index, builderForValue.build());
        onChanged();
      } else {
        asksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public Builder addAllAsks(
        java.lang.Iterable<? extends rs.raf.pds.v5.z2.gRPC.AskData> values) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, asks_);
        onChanged();
      } else {
        asksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public Builder clearAsks() {
      if (asksBuilder_ == null) {
        asks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        asksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public Builder removeAsks(int index) {
      if (asksBuilder_ == null) {
        ensureAsksIsMutable();
        asks_.remove(index);
        onChanged();
      } else {
        asksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.AskData.Builder getAsksBuilder(
        int index) {
      return getAsksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.AskDataOrBuilder getAsksOrBuilder(
        int index) {
      if (asksBuilder_ == null) {
        return asks_.get(index);  } else {
        return asksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public java.util.List<? extends rs.raf.pds.v5.z2.gRPC.AskDataOrBuilder> 
         getAsksOrBuilderList() {
      if (asksBuilder_ != null) {
        return asksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(asks_);
      }
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.AskData.Builder addAsksBuilder() {
      return getAsksFieldBuilder().addBuilder(
          rs.raf.pds.v5.z2.gRPC.AskData.getDefaultInstance());
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.AskData.Builder addAsksBuilder(
        int index) {
      return getAsksFieldBuilder().addBuilder(
          index, rs.raf.pds.v5.z2.gRPC.AskData.getDefaultInstance());
    }
    /**
     * <code>repeated .AskData asks = 1;</code>
     */
    public java.util.List<rs.raf.pds.v5.z2.gRPC.AskData.Builder> 
         getAsksBuilderList() {
      return getAsksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.v5.z2.gRPC.AskData, rs.raf.pds.v5.z2.gRPC.AskData.Builder, rs.raf.pds.v5.z2.gRPC.AskDataOrBuilder> 
        getAsksFieldBuilder() {
      if (asksBuilder_ == null) {
        asksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            rs.raf.pds.v5.z2.gRPC.AskData, rs.raf.pds.v5.z2.gRPC.AskData.Builder, rs.raf.pds.v5.z2.gRPC.AskDataOrBuilder>(
                asks_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        asks_ = null;
      }
      return asksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AskList)
  }

  // @@protoc_insertion_point(class_scope:AskList)
  private static final rs.raf.pds.v5.z2.gRPC.AskList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.v5.z2.gRPC.AskList();
  }

  public static rs.raf.pds.v5.z2.gRPC.AskList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AskList>
      PARSER = new com.google.protobuf.AbstractParser<AskList>() {
    @java.lang.Override
    public AskList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AskList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AskList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.AskList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

