// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_exchange.proto

// Protobuf Java Version: 3.25.1
package rs.raf.pds.v5.z2.gRPC;

public interface AskListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AskList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  java.util.List<rs.raf.pds.v5.z2.gRPC.AskData> 
      getAsksList();
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.AskData getAsks(int index);
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  int getAsksCount();
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  java.util.List<? extends rs.raf.pds.v5.z2.gRPC.AskDataOrBuilder> 
      getAsksOrBuilderList();
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.AskDataOrBuilder getAsksOrBuilder(
      int index);
}
