// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_exchange.proto

// Protobuf Java Version: 3.25.1
package rs.raf.pds.v5.z2.gRPC;

/**
 * Protobuf type {@code ClientPortfolio}
 */
public final class ClientPortfolio extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ClientPortfolio)
    ClientPortfolioOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientPortfolio.newBuilder() to construct.
  private ClientPortfolio(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientPortfolio() {
    clientId_ = "";
    stocks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientPortfolio();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_ClientPortfolio_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_ClientPortfolio_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.v5.z2.gRPC.ClientPortfolio.class, rs.raf.pds.v5.z2.gRPC.ClientPortfolio.Builder.class);
  }

  public static final int CLIENTID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientId_ = "";
  /**
   * <code>string clientId = 1;</code>
   * @return The clientId.
   */
  @java.lang.Override
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <code>string clientId = 1;</code>
   * @return The bytes for clientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STOCKS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<rs.raf.pds.v5.z2.gRPC.ClientStock> stocks_;
  /**
   * <code>repeated .ClientStock stocks = 2;</code>
   */
  @java.lang.Override
  public java.util.List<rs.raf.pds.v5.z2.gRPC.ClientStock> getStocksList() {
    return stocks_;
  }
  /**
   * <code>repeated .ClientStock stocks = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends rs.raf.pds.v5.z2.gRPC.ClientStockOrBuilder> 
      getStocksOrBuilderList() {
    return stocks_;
  }
  /**
   * <code>repeated .ClientStock stocks = 2;</code>
   */
  @java.lang.Override
  public int getStocksCount() {
    return stocks_.size();
  }
  /**
   * <code>repeated .ClientStock stocks = 2;</code>
   */
  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.ClientStock getStocks(int index) {
    return stocks_.get(index);
  }
  /**
   * <code>repeated .ClientStock stocks = 2;</code>
   */
  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.ClientStockOrBuilder getStocksOrBuilder(
      int index) {
    return stocks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
    }
    for (int i = 0; i < stocks_.size(); i++) {
      output.writeMessage(2, stocks_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
    }
    for (int i = 0; i < stocks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, stocks_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.v5.z2.gRPC.ClientPortfolio)) {
      return super.equals(obj);
    }
    rs.raf.pds.v5.z2.gRPC.ClientPortfolio other = (rs.raf.pds.v5.z2.gRPC.ClientPortfolio) obj;

    if (!getClientId()
        .equals(other.getClientId())) return false;
    if (!getStocksList()
        .equals(other.getStocksList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    if (getStocksCount() > 0) {
      hash = (37 * hash) + STOCKS_FIELD_NUMBER;
      hash = (53 * hash) + getStocksList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.v5.z2.gRPC.ClientPortfolio prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ClientPortfolio}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ClientPortfolio)
      rs.raf.pds.v5.z2.gRPC.ClientPortfolioOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_ClientPortfolio_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_ClientPortfolio_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.v5.z2.gRPC.ClientPortfolio.class, rs.raf.pds.v5.z2.gRPC.ClientPortfolio.Builder.class);
    }

    // Construct using rs.raf.pds.v5.z2.gRPC.ClientPortfolio.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      clientId_ = "";
      if (stocksBuilder_ == null) {
        stocks_ = java.util.Collections.emptyList();
      } else {
        stocks_ = null;
        stocksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_ClientPortfolio_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.ClientPortfolio getDefaultInstanceForType() {
      return rs.raf.pds.v5.z2.gRPC.ClientPortfolio.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.ClientPortfolio build() {
      rs.raf.pds.v5.z2.gRPC.ClientPortfolio result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.ClientPortfolio buildPartial() {
      rs.raf.pds.v5.z2.gRPC.ClientPortfolio result = new rs.raf.pds.v5.z2.gRPC.ClientPortfolio(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(rs.raf.pds.v5.z2.gRPC.ClientPortfolio result) {
      if (stocksBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          stocks_ = java.util.Collections.unmodifiableList(stocks_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.stocks_ = stocks_;
      } else {
        result.stocks_ = stocksBuilder_.build();
      }
    }

    private void buildPartial0(rs.raf.pds.v5.z2.gRPC.ClientPortfolio result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.clientId_ = clientId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.v5.z2.gRPC.ClientPortfolio) {
        return mergeFrom((rs.raf.pds.v5.z2.gRPC.ClientPortfolio)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.v5.z2.gRPC.ClientPortfolio other) {
      if (other == rs.raf.pds.v5.z2.gRPC.ClientPortfolio.getDefaultInstance()) return this;
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (stocksBuilder_ == null) {
        if (!other.stocks_.isEmpty()) {
          if (stocks_.isEmpty()) {
            stocks_ = other.stocks_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStocksIsMutable();
            stocks_.addAll(other.stocks_);
          }
          onChanged();
        }
      } else {
        if (!other.stocks_.isEmpty()) {
          if (stocksBuilder_.isEmpty()) {
            stocksBuilder_.dispose();
            stocksBuilder_ = null;
            stocks_ = other.stocks_;
            bitField0_ = (bitField0_ & ~0x00000002);
            stocksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStocksFieldBuilder() : null;
          } else {
            stocksBuilder_.addAllMessages(other.stocks_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              clientId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              rs.raf.pds.v5.z2.gRPC.ClientStock m =
                  input.readMessage(
                      rs.raf.pds.v5.z2.gRPC.ClientStock.parser(),
                      extensionRegistry);
              if (stocksBuilder_ == null) {
                ensureStocksIsMutable();
                stocks_.add(m);
              } else {
                stocksBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object clientId_ = "";
    /**
     * <code>string clientId = 1;</code>
     * @return The clientId.
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clientId = 1;</code>
     * @return The bytes for clientId.
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientId = 1;</code>
     * @param value The clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string clientId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientId() {
      clientId_ = getDefaultInstance().getClientId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string clientId = 1;</code>
     * @param value The bytes for clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<rs.raf.pds.v5.z2.gRPC.ClientStock> stocks_ =
      java.util.Collections.emptyList();
    private void ensureStocksIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        stocks_ = new java.util.ArrayList<rs.raf.pds.v5.z2.gRPC.ClientStock>(stocks_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.v5.z2.gRPC.ClientStock, rs.raf.pds.v5.z2.gRPC.ClientStock.Builder, rs.raf.pds.v5.z2.gRPC.ClientStockOrBuilder> stocksBuilder_;

    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public java.util.List<rs.raf.pds.v5.z2.gRPC.ClientStock> getStocksList() {
      if (stocksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stocks_);
      } else {
        return stocksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public int getStocksCount() {
      if (stocksBuilder_ == null) {
        return stocks_.size();
      } else {
        return stocksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.ClientStock getStocks(int index) {
      if (stocksBuilder_ == null) {
        return stocks_.get(index);
      } else {
        return stocksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public Builder setStocks(
        int index, rs.raf.pds.v5.z2.gRPC.ClientStock value) {
      if (stocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStocksIsMutable();
        stocks_.set(index, value);
        onChanged();
      } else {
        stocksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public Builder setStocks(
        int index, rs.raf.pds.v5.z2.gRPC.ClientStock.Builder builderForValue) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        stocks_.set(index, builderForValue.build());
        onChanged();
      } else {
        stocksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public Builder addStocks(rs.raf.pds.v5.z2.gRPC.ClientStock value) {
      if (stocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStocksIsMutable();
        stocks_.add(value);
        onChanged();
      } else {
        stocksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public Builder addStocks(
        int index, rs.raf.pds.v5.z2.gRPC.ClientStock value) {
      if (stocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStocksIsMutable();
        stocks_.add(index, value);
        onChanged();
      } else {
        stocksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public Builder addStocks(
        rs.raf.pds.v5.z2.gRPC.ClientStock.Builder builderForValue) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        stocks_.add(builderForValue.build());
        onChanged();
      } else {
        stocksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public Builder addStocks(
        int index, rs.raf.pds.v5.z2.gRPC.ClientStock.Builder builderForValue) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        stocks_.add(index, builderForValue.build());
        onChanged();
      } else {
        stocksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public Builder addAllStocks(
        java.lang.Iterable<? extends rs.raf.pds.v5.z2.gRPC.ClientStock> values) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stocks_);
        onChanged();
      } else {
        stocksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public Builder clearStocks() {
      if (stocksBuilder_ == null) {
        stocks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        stocksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public Builder removeStocks(int index) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        stocks_.remove(index);
        onChanged();
      } else {
        stocksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.ClientStock.Builder getStocksBuilder(
        int index) {
      return getStocksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.ClientStockOrBuilder getStocksOrBuilder(
        int index) {
      if (stocksBuilder_ == null) {
        return stocks_.get(index);  } else {
        return stocksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public java.util.List<? extends rs.raf.pds.v5.z2.gRPC.ClientStockOrBuilder> 
         getStocksOrBuilderList() {
      if (stocksBuilder_ != null) {
        return stocksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stocks_);
      }
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.ClientStock.Builder addStocksBuilder() {
      return getStocksFieldBuilder().addBuilder(
          rs.raf.pds.v5.z2.gRPC.ClientStock.getDefaultInstance());
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.ClientStock.Builder addStocksBuilder(
        int index) {
      return getStocksFieldBuilder().addBuilder(
          index, rs.raf.pds.v5.z2.gRPC.ClientStock.getDefaultInstance());
    }
    /**
     * <code>repeated .ClientStock stocks = 2;</code>
     */
    public java.util.List<rs.raf.pds.v5.z2.gRPC.ClientStock.Builder> 
         getStocksBuilderList() {
      return getStocksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.v5.z2.gRPC.ClientStock, rs.raf.pds.v5.z2.gRPC.ClientStock.Builder, rs.raf.pds.v5.z2.gRPC.ClientStockOrBuilder> 
        getStocksFieldBuilder() {
      if (stocksBuilder_ == null) {
        stocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            rs.raf.pds.v5.z2.gRPC.ClientStock, rs.raf.pds.v5.z2.gRPC.ClientStock.Builder, rs.raf.pds.v5.z2.gRPC.ClientStockOrBuilder>(
                stocks_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        stocks_ = null;
      }
      return stocksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ClientPortfolio)
  }

  // @@protoc_insertion_point(class_scope:ClientPortfolio)
  private static final rs.raf.pds.v5.z2.gRPC.ClientPortfolio DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.v5.z2.gRPC.ClientPortfolio();
  }

  public static rs.raf.pds.v5.z2.gRPC.ClientPortfolio getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientPortfolio>
      PARSER = new com.google.protobuf.AbstractParser<ClientPortfolio>() {
    @java.lang.Override
    public ClientPortfolio parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClientPortfolio> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientPortfolio> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.ClientPortfolio getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

