// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_exchange.proto

// Protobuf Java Version: 3.25.1
package rs.raf.pds.v5.z2.gRPC;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.OrderData order = 1;</code>
   * @return Whether the order field is set.
   */
  boolean hasOrder();
  /**
   * <code>.OrderData order = 1;</code>
   * @return The order.
   */
  rs.raf.pds.v5.z2.gRPC.OrderData getOrder();
  /**
   * <code>.OrderData order = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.OrderDataOrBuilder getOrderOrBuilder();
}
