// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_exchange.proto

// Protobuf Java Version: 3.25.1
package rs.raf.pds.v5.z2.gRPC;

/**
 * Protobuf type {@code StockDataList}
 */
public final class StockDataList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StockDataList)
    StockDataListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StockDataList.newBuilder() to construct.
  private StockDataList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StockDataList() {
    stocks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StockDataList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_StockDataList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_StockDataList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.v5.z2.gRPC.StockDataList.class, rs.raf.pds.v5.z2.gRPC.StockDataList.Builder.class);
  }

  public static final int STOCKS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<rs.raf.pds.v5.z2.gRPC.StockData> stocks_;
  /**
   * <code>repeated .StockData stocks = 1;</code>
   */
  @java.lang.Override
  public java.util.List<rs.raf.pds.v5.z2.gRPC.StockData> getStocksList() {
    return stocks_;
  }
  /**
   * <code>repeated .StockData stocks = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends rs.raf.pds.v5.z2.gRPC.StockDataOrBuilder> 
      getStocksOrBuilderList() {
    return stocks_;
  }
  /**
   * <code>repeated .StockData stocks = 1;</code>
   */
  @java.lang.Override
  public int getStocksCount() {
    return stocks_.size();
  }
  /**
   * <code>repeated .StockData stocks = 1;</code>
   */
  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.StockData getStocks(int index) {
    return stocks_.get(index);
  }
  /**
   * <code>repeated .StockData stocks = 1;</code>
   */
  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.StockDataOrBuilder getStocksOrBuilder(
      int index) {
    return stocks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < stocks_.size(); i++) {
      output.writeMessage(1, stocks_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < stocks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, stocks_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.v5.z2.gRPC.StockDataList)) {
      return super.equals(obj);
    }
    rs.raf.pds.v5.z2.gRPC.StockDataList other = (rs.raf.pds.v5.z2.gRPC.StockDataList) obj;

    if (!getStocksList()
        .equals(other.getStocksList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStocksCount() > 0) {
      hash = (37 * hash) + STOCKS_FIELD_NUMBER;
      hash = (53 * hash) + getStocksList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.v5.z2.gRPC.StockDataList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockDataList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockDataList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockDataList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockDataList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockDataList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockDataList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockDataList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static rs.raf.pds.v5.z2.gRPC.StockDataList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static rs.raf.pds.v5.z2.gRPC.StockDataList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockDataList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.StockDataList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.v5.z2.gRPC.StockDataList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code StockDataList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StockDataList)
      rs.raf.pds.v5.z2.gRPC.StockDataListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_StockDataList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_StockDataList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.v5.z2.gRPC.StockDataList.class, rs.raf.pds.v5.z2.gRPC.StockDataList.Builder.class);
    }

    // Construct using rs.raf.pds.v5.z2.gRPC.StockDataList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (stocksBuilder_ == null) {
        stocks_ = java.util.Collections.emptyList();
      } else {
        stocks_ = null;
        stocksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_StockDataList_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.StockDataList getDefaultInstanceForType() {
      return rs.raf.pds.v5.z2.gRPC.StockDataList.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.StockDataList build() {
      rs.raf.pds.v5.z2.gRPC.StockDataList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.StockDataList buildPartial() {
      rs.raf.pds.v5.z2.gRPC.StockDataList result = new rs.raf.pds.v5.z2.gRPC.StockDataList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(rs.raf.pds.v5.z2.gRPC.StockDataList result) {
      if (stocksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          stocks_ = java.util.Collections.unmodifiableList(stocks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.stocks_ = stocks_;
      } else {
        result.stocks_ = stocksBuilder_.build();
      }
    }

    private void buildPartial0(rs.raf.pds.v5.z2.gRPC.StockDataList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.v5.z2.gRPC.StockDataList) {
        return mergeFrom((rs.raf.pds.v5.z2.gRPC.StockDataList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.v5.z2.gRPC.StockDataList other) {
      if (other == rs.raf.pds.v5.z2.gRPC.StockDataList.getDefaultInstance()) return this;
      if (stocksBuilder_ == null) {
        if (!other.stocks_.isEmpty()) {
          if (stocks_.isEmpty()) {
            stocks_ = other.stocks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStocksIsMutable();
            stocks_.addAll(other.stocks_);
          }
          onChanged();
        }
      } else {
        if (!other.stocks_.isEmpty()) {
          if (stocksBuilder_.isEmpty()) {
            stocksBuilder_.dispose();
            stocksBuilder_ = null;
            stocks_ = other.stocks_;
            bitField0_ = (bitField0_ & ~0x00000001);
            stocksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStocksFieldBuilder() : null;
          } else {
            stocksBuilder_.addAllMessages(other.stocks_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              rs.raf.pds.v5.z2.gRPC.StockData m =
                  input.readMessage(
                      rs.raf.pds.v5.z2.gRPC.StockData.parser(),
                      extensionRegistry);
              if (stocksBuilder_ == null) {
                ensureStocksIsMutable();
                stocks_.add(m);
              } else {
                stocksBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<rs.raf.pds.v5.z2.gRPC.StockData> stocks_ =
      java.util.Collections.emptyList();
    private void ensureStocksIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        stocks_ = new java.util.ArrayList<rs.raf.pds.v5.z2.gRPC.StockData>(stocks_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.v5.z2.gRPC.StockData, rs.raf.pds.v5.z2.gRPC.StockData.Builder, rs.raf.pds.v5.z2.gRPC.StockDataOrBuilder> stocksBuilder_;

    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public java.util.List<rs.raf.pds.v5.z2.gRPC.StockData> getStocksList() {
      if (stocksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stocks_);
      } else {
        return stocksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public int getStocksCount() {
      if (stocksBuilder_ == null) {
        return stocks_.size();
      } else {
        return stocksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.StockData getStocks(int index) {
      if (stocksBuilder_ == null) {
        return stocks_.get(index);
      } else {
        return stocksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public Builder setStocks(
        int index, rs.raf.pds.v5.z2.gRPC.StockData value) {
      if (stocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStocksIsMutable();
        stocks_.set(index, value);
        onChanged();
      } else {
        stocksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public Builder setStocks(
        int index, rs.raf.pds.v5.z2.gRPC.StockData.Builder builderForValue) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        stocks_.set(index, builderForValue.build());
        onChanged();
      } else {
        stocksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public Builder addStocks(rs.raf.pds.v5.z2.gRPC.StockData value) {
      if (stocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStocksIsMutable();
        stocks_.add(value);
        onChanged();
      } else {
        stocksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public Builder addStocks(
        int index, rs.raf.pds.v5.z2.gRPC.StockData value) {
      if (stocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStocksIsMutable();
        stocks_.add(index, value);
        onChanged();
      } else {
        stocksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public Builder addStocks(
        rs.raf.pds.v5.z2.gRPC.StockData.Builder builderForValue) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        stocks_.add(builderForValue.build());
        onChanged();
      } else {
        stocksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public Builder addStocks(
        int index, rs.raf.pds.v5.z2.gRPC.StockData.Builder builderForValue) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        stocks_.add(index, builderForValue.build());
        onChanged();
      } else {
        stocksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public Builder addAllStocks(
        java.lang.Iterable<? extends rs.raf.pds.v5.z2.gRPC.StockData> values) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stocks_);
        onChanged();
      } else {
        stocksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public Builder clearStocks() {
      if (stocksBuilder_ == null) {
        stocks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        stocksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public Builder removeStocks(int index) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        stocks_.remove(index);
        onChanged();
      } else {
        stocksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.StockData.Builder getStocksBuilder(
        int index) {
      return getStocksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.StockDataOrBuilder getStocksOrBuilder(
        int index) {
      if (stocksBuilder_ == null) {
        return stocks_.get(index);  } else {
        return stocksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public java.util.List<? extends rs.raf.pds.v5.z2.gRPC.StockDataOrBuilder> 
         getStocksOrBuilderList() {
      if (stocksBuilder_ != null) {
        return stocksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stocks_);
      }
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.StockData.Builder addStocksBuilder() {
      return getStocksFieldBuilder().addBuilder(
          rs.raf.pds.v5.z2.gRPC.StockData.getDefaultInstance());
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.StockData.Builder addStocksBuilder(
        int index) {
      return getStocksFieldBuilder().addBuilder(
          index, rs.raf.pds.v5.z2.gRPC.StockData.getDefaultInstance());
    }
    /**
     * <code>repeated .StockData stocks = 1;</code>
     */
    public java.util.List<rs.raf.pds.v5.z2.gRPC.StockData.Builder> 
         getStocksBuilderList() {
      return getStocksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.v5.z2.gRPC.StockData, rs.raf.pds.v5.z2.gRPC.StockData.Builder, rs.raf.pds.v5.z2.gRPC.StockDataOrBuilder> 
        getStocksFieldBuilder() {
      if (stocksBuilder_ == null) {
        stocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            rs.raf.pds.v5.z2.gRPC.StockData, rs.raf.pds.v5.z2.gRPC.StockData.Builder, rs.raf.pds.v5.z2.gRPC.StockDataOrBuilder>(
                stocks_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        stocks_ = null;
      }
      return stocksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StockDataList)
  }

  // @@protoc_insertion_point(class_scope:StockDataList)
  private static final rs.raf.pds.v5.z2.gRPC.StockDataList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.v5.z2.gRPC.StockDataList();
  }

  public static rs.raf.pds.v5.z2.gRPC.StockDataList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StockDataList>
      PARSER = new com.google.protobuf.AbstractParser<StockDataList>() {
    @java.lang.Override
    public StockDataList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StockDataList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StockDataList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.StockDataList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

