// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_exchange.proto

// Protobuf Java Version: 3.25.1
package rs.raf.pds.v5.z2.gRPC;

public interface StockDataListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockDataList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .StockData stocks = 1;</code>
   */
  java.util.List<rs.raf.pds.v5.z2.gRPC.StockData> 
      getStocksList();
  /**
   * <code>repeated .StockData stocks = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.StockData getStocks(int index);
  /**
   * <code>repeated .StockData stocks = 1;</code>
   */
  int getStocksCount();
  /**
   * <code>repeated .StockData stocks = 1;</code>
   */
  java.util.List<? extends rs.raf.pds.v5.z2.gRPC.StockDataOrBuilder> 
      getStocksOrBuilderList();
  /**
   * <code>repeated .StockData stocks = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.StockDataOrBuilder getStocksOrBuilder(
      int index);
}
