// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_exchange.proto

// Protobuf Java Version: 3.25.1
package rs.raf.pds.v5.z2.gRPC;

/**
 * Protobuf type {@code TradeList}
 */
public final class TradeList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TradeList)
    TradeListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TradeList.newBuilder() to construct.
  private TradeList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TradeList() {
    trades_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TradeList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_TradeList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_TradeList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.v5.z2.gRPC.TradeList.class, rs.raf.pds.v5.z2.gRPC.TradeList.Builder.class);
  }

  public static final int TRADES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<rs.raf.pds.v5.z2.gRPC.Trade> trades_;
  /**
   * <code>repeated .Trade trades = 1;</code>
   */
  @java.lang.Override
  public java.util.List<rs.raf.pds.v5.z2.gRPC.Trade> getTradesList() {
    return trades_;
  }
  /**
   * <code>repeated .Trade trades = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends rs.raf.pds.v5.z2.gRPC.TradeOrBuilder> 
      getTradesOrBuilderList() {
    return trades_;
  }
  /**
   * <code>repeated .Trade trades = 1;</code>
   */
  @java.lang.Override
  public int getTradesCount() {
    return trades_.size();
  }
  /**
   * <code>repeated .Trade trades = 1;</code>
   */
  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.Trade getTrades(int index) {
    return trades_.get(index);
  }
  /**
   * <code>repeated .Trade trades = 1;</code>
   */
  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.TradeOrBuilder getTradesOrBuilder(
      int index) {
    return trades_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < trades_.size(); i++) {
      output.writeMessage(1, trades_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < trades_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, trades_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.v5.z2.gRPC.TradeList)) {
      return super.equals(obj);
    }
    rs.raf.pds.v5.z2.gRPC.TradeList other = (rs.raf.pds.v5.z2.gRPC.TradeList) obj;

    if (!getTradesList()
        .equals(other.getTradesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTradesCount() > 0) {
      hash = (37 * hash) + TRADES_FIELD_NUMBER;
      hash = (53 * hash) + getTradesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.v5.z2.gRPC.TradeList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.TradeList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.TradeList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.TradeList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.TradeList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.TradeList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.TradeList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.TradeList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static rs.raf.pds.v5.z2.gRPC.TradeList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static rs.raf.pds.v5.z2.gRPC.TradeList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.TradeList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.TradeList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.v5.z2.gRPC.TradeList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TradeList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TradeList)
      rs.raf.pds.v5.z2.gRPC.TradeListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_TradeList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_TradeList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.v5.z2.gRPC.TradeList.class, rs.raf.pds.v5.z2.gRPC.TradeList.Builder.class);
    }

    // Construct using rs.raf.pds.v5.z2.gRPC.TradeList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (tradesBuilder_ == null) {
        trades_ = java.util.Collections.emptyList();
      } else {
        trades_ = null;
        tradesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.v5.z2.gRPC.StockExchange.internal_static_TradeList_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.TradeList getDefaultInstanceForType() {
      return rs.raf.pds.v5.z2.gRPC.TradeList.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.TradeList build() {
      rs.raf.pds.v5.z2.gRPC.TradeList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.TradeList buildPartial() {
      rs.raf.pds.v5.z2.gRPC.TradeList result = new rs.raf.pds.v5.z2.gRPC.TradeList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(rs.raf.pds.v5.z2.gRPC.TradeList result) {
      if (tradesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          trades_ = java.util.Collections.unmodifiableList(trades_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.trades_ = trades_;
      } else {
        result.trades_ = tradesBuilder_.build();
      }
    }

    private void buildPartial0(rs.raf.pds.v5.z2.gRPC.TradeList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.v5.z2.gRPC.TradeList) {
        return mergeFrom((rs.raf.pds.v5.z2.gRPC.TradeList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.v5.z2.gRPC.TradeList other) {
      if (other == rs.raf.pds.v5.z2.gRPC.TradeList.getDefaultInstance()) return this;
      if (tradesBuilder_ == null) {
        if (!other.trades_.isEmpty()) {
          if (trades_.isEmpty()) {
            trades_ = other.trades_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTradesIsMutable();
            trades_.addAll(other.trades_);
          }
          onChanged();
        }
      } else {
        if (!other.trades_.isEmpty()) {
          if (tradesBuilder_.isEmpty()) {
            tradesBuilder_.dispose();
            tradesBuilder_ = null;
            trades_ = other.trades_;
            bitField0_ = (bitField0_ & ~0x00000001);
            tradesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTradesFieldBuilder() : null;
          } else {
            tradesBuilder_.addAllMessages(other.trades_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              rs.raf.pds.v5.z2.gRPC.Trade m =
                  input.readMessage(
                      rs.raf.pds.v5.z2.gRPC.Trade.parser(),
                      extensionRegistry);
              if (tradesBuilder_ == null) {
                ensureTradesIsMutable();
                trades_.add(m);
              } else {
                tradesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<rs.raf.pds.v5.z2.gRPC.Trade> trades_ =
      java.util.Collections.emptyList();
    private void ensureTradesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        trades_ = new java.util.ArrayList<rs.raf.pds.v5.z2.gRPC.Trade>(trades_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.v5.z2.gRPC.Trade, rs.raf.pds.v5.z2.gRPC.Trade.Builder, rs.raf.pds.v5.z2.gRPC.TradeOrBuilder> tradesBuilder_;

    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public java.util.List<rs.raf.pds.v5.z2.gRPC.Trade> getTradesList() {
      if (tradesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(trades_);
      } else {
        return tradesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public int getTradesCount() {
      if (tradesBuilder_ == null) {
        return trades_.size();
      } else {
        return tradesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.Trade getTrades(int index) {
      if (tradesBuilder_ == null) {
        return trades_.get(index);
      } else {
        return tradesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public Builder setTrades(
        int index, rs.raf.pds.v5.z2.gRPC.Trade value) {
      if (tradesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTradesIsMutable();
        trades_.set(index, value);
        onChanged();
      } else {
        tradesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public Builder setTrades(
        int index, rs.raf.pds.v5.z2.gRPC.Trade.Builder builderForValue) {
      if (tradesBuilder_ == null) {
        ensureTradesIsMutable();
        trades_.set(index, builderForValue.build());
        onChanged();
      } else {
        tradesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public Builder addTrades(rs.raf.pds.v5.z2.gRPC.Trade value) {
      if (tradesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTradesIsMutable();
        trades_.add(value);
        onChanged();
      } else {
        tradesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public Builder addTrades(
        int index, rs.raf.pds.v5.z2.gRPC.Trade value) {
      if (tradesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTradesIsMutable();
        trades_.add(index, value);
        onChanged();
      } else {
        tradesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public Builder addTrades(
        rs.raf.pds.v5.z2.gRPC.Trade.Builder builderForValue) {
      if (tradesBuilder_ == null) {
        ensureTradesIsMutable();
        trades_.add(builderForValue.build());
        onChanged();
      } else {
        tradesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public Builder addTrades(
        int index, rs.raf.pds.v5.z2.gRPC.Trade.Builder builderForValue) {
      if (tradesBuilder_ == null) {
        ensureTradesIsMutable();
        trades_.add(index, builderForValue.build());
        onChanged();
      } else {
        tradesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public Builder addAllTrades(
        java.lang.Iterable<? extends rs.raf.pds.v5.z2.gRPC.Trade> values) {
      if (tradesBuilder_ == null) {
        ensureTradesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, trades_);
        onChanged();
      } else {
        tradesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public Builder clearTrades() {
      if (tradesBuilder_ == null) {
        trades_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        tradesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public Builder removeTrades(int index) {
      if (tradesBuilder_ == null) {
        ensureTradesIsMutable();
        trades_.remove(index);
        onChanged();
      } else {
        tradesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.Trade.Builder getTradesBuilder(
        int index) {
      return getTradesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.TradeOrBuilder getTradesOrBuilder(
        int index) {
      if (tradesBuilder_ == null) {
        return trades_.get(index);  } else {
        return tradesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public java.util.List<? extends rs.raf.pds.v5.z2.gRPC.TradeOrBuilder> 
         getTradesOrBuilderList() {
      if (tradesBuilder_ != null) {
        return tradesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(trades_);
      }
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.Trade.Builder addTradesBuilder() {
      return getTradesFieldBuilder().addBuilder(
          rs.raf.pds.v5.z2.gRPC.Trade.getDefaultInstance());
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.Trade.Builder addTradesBuilder(
        int index) {
      return getTradesFieldBuilder().addBuilder(
          index, rs.raf.pds.v5.z2.gRPC.Trade.getDefaultInstance());
    }
    /**
     * <code>repeated .Trade trades = 1;</code>
     */
    public java.util.List<rs.raf.pds.v5.z2.gRPC.Trade.Builder> 
         getTradesBuilderList() {
      return getTradesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.v5.z2.gRPC.Trade, rs.raf.pds.v5.z2.gRPC.Trade.Builder, rs.raf.pds.v5.z2.gRPC.TradeOrBuilder> 
        getTradesFieldBuilder() {
      if (tradesBuilder_ == null) {
        tradesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            rs.raf.pds.v5.z2.gRPC.Trade, rs.raf.pds.v5.z2.gRPC.Trade.Builder, rs.raf.pds.v5.z2.gRPC.TradeOrBuilder>(
                trades_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        trades_ = null;
      }
      return tradesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TradeList)
  }

  // @@protoc_insertion_point(class_scope:TradeList)
  private static final rs.raf.pds.v5.z2.gRPC.TradeList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.v5.z2.gRPC.TradeList();
  }

  public static rs.raf.pds.v5.z2.gRPC.TradeList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TradeList>
      PARSER = new com.google.protobuf.AbstractParser<TradeList>() {
    @java.lang.Override
    public TradeList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TradeList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TradeList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.TradeList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

